#Splash screen properties
#Wed Jul 24 17:11:40 CEST 2024
logoTexture=textures/gui/title/mojang.png
background=0x354345
font=0xB2BDBF
barBackground=0x354345
barBorder=0x354345
rotate=false
bar=0xCB3D35
enabled=true
resourcePackPath=resources
logoOffset=30
forgeTexture=fml\:textures/gui/forgi.gif
fontTexture=textures/font/ascii.png
